export const users = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    role: 'USER',
    email: 'alice@example.com',
    firstName: 'Alice',
    lastName: 'Johnson',
    password: 'hashedpassword123',
    imageUrl: 'https://example.com/alice.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    role: 'USER',
    email: 'kevinromero',
    firstName: 'Bob',
    lastName: 'Smith',
    password: '12345',
    imageUrl: 'https://example.com/bob.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    role: 'ADMIN',
    email: 'charlie@example.com',
    firstName: 'Charlie',
    lastName: 'Brown',
    password: 'hashedpassword789',
    imageUrl: 'https://example.com/charlie.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    role: 'USER',
    email: 'dave@example.com',
    firstName: 'Dave',
    lastName: 'Miller',
    password: 'hashedpassword101',
    imageUrl: 'https://example.com/dave.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440005',
    role: 'USER',
    email: 'emma@example.com',
    firstName: 'Emma',
    lastName: 'Wilson',
    password: 'hashedpassword202',
    imageUrl: 'https://example.com/emma.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440006',
    role: 'USER',
    email: 'frank@example.com',
    firstName: 'Frank',
    lastName: 'Taylor',
    password: 'hashedpassword303',
    imageUrl: 'https://example.com/frank.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440007',
    role: 'USER',
    email: 'grace@example.com',
    firstName: 'Grace',
    lastName: 'Anderson',
    password: 'hashedpassword404',
    imageUrl: 'https://example.com/grace.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440008',
    role: 'ADMIN',
    email: 'henry@example.com',
    firstName: 'Henry',
    lastName: 'Moore',
    password: 'hashedpassword505',
    imageUrl: 'https://example.com/henry.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440009',
    role: 'USER',
    email: 'isabella@example.com',
    firstName: 'Isabella',
    lastName: 'White',
    password: 'hashedpassword606',
    imageUrl: 'https://example.com/isabella.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440010',
    role: 'USER',
    email: 'jackson@example.com',
    firstName: 'Jackson',
    lastName: 'Harris',
    password: 'hashedpassword707',
    imageUrl: 'https://example.com/jackson.jpg',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const inventoryData = [
  {
    id: 'log_001',
    timestamp: '2025-03-27T10:30:00Z',
    user: {
      id: 'user_123',
      name: 'John Doe',
      role: 'Admin',
    },
    action: 'Add',
    details: {
      product_id: 'prod_567',
      product_name: 'Wireless Mouse',
      category: 'Electronics',
      quantity_added: 50,
      current_stock: 150,
      product_image:
        'https://placehold.co/600x400/000000/FFFFFF/png?text=Wireless+Mouse',
    },
  },
  {
    id: 'log_002',
    timestamp: '2025-03-27T11:00:00Z',
    user: {
      id: 'user_456',
      name: 'Jane Smith',
      role: 'Manager',
    },
    action: 'Updated',
    details: {
      product_id: 'prod_890',
      product_name: 'Office Chair',
      previous_stock: 20,
      new_stock: 35,
      product_image:
        'https://placehold.co/600x400/000000/FFFFFF/png?text=Office+Chair',
    },
  },
  {
    id: 'log_003',
    timestamp: '2025-03-27T11:45:00Z',
    user: {
      id: 'user_789',
      name: 'Emily Johnson',
      role: 'Employee',
    },
    action: 'Add',
    details: {
      product_id: 'prod_234',
      product_name: 'USB-C Cable',
      category: 'Electronics',
      quantity_added: 50,
      current_stock: 150,
      product_image:
        'https://placehold.co/600x400/000000/FFFFFF/png?text=USB-C+Cable',
    },
  },
]
